{{- $clustername := .Values.cluster.name }}
apiVersion: rke-machine-config.cattle.io/v1
kind: Amazonec2Config
metadata:
  name: {{ $clustername }}-controlplane
  namespace: fleet-default
instanceType: t3.micro
region: us-east-1
subnetId: subnet-05e9d48a08266e8f3
vpcId: vpc-01bc080b5ceef796d
zone: a
sshUser: ubuntu
